### PR TITLE
Add Marching Ants animation to docs

### PR DESCRIPTION
**Pull request by Alero-Awani**
**Notes for Reviewers**

This PR fixes #337

Also changed the embedded design in the Embedding Designs doc to a better design.

image

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by fitzergerald — APPROVED** [review]
LGTM

**Review by leecalcote — COMMENTED** [review]
Quality work, @Alero-Awani.

Is there an existing section with code snippet that needs to be replaced?

**Comment by leecalcote** [comment]
> Quality work, @Alero-Awani.
> 
> Is there an existing section with code snippet that needs to be replaced?

I thought that we had a yaml or json example in here somewhere. It can make sense to continue to have as a behind-the-scenes way of setting this animation (instead of using the mouse to do it), but we'll need to make sure the it is still set in the same way. I don't think that it is. Soooo, we'll either need to delete or update.

**Comment by vishalvivekm** [comment]
@Alero-Awani 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by vishalvivekm** [comment]
> @Alero-Awani Thank you for your contribution! Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).
> 
> Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

adding

**Comment by leecalcote** [comment]
> Quality work, @Alero-Awani.
> 
> Is there an existing section with code snippet that needs to be replaced?

**Comment by Alero-Awani** [comment]
@leecalcote This [embedded design](https://docs.layer5.io/kanvas/designer/embedding-designs/) needs to be replaced with a more complex design. I'll do that and include it in this PR.

**Pull request merged**
