### PR TITLE
fixing communitybook image

### LINKED ISSUE #120: [Home] Image escaping its container
#### Current Behavior
On the home page, there is a container-escaping community handbook image.

#### Expected Behavior
Image should fit to container bounds.

#### Screenshots/Logs
Screenshot 2023-12-28 at 9 57 44 AM

#### Environment

- **Host OS:** Mac 

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by vaibhavpnimkar**
**Notes for Reviewers**

This PR fixes #120 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by vaibhavpnimkar** [comment]
its just dco check i forgot to add -"s " while commiting plz ignore that @leecalcote  @Yashsharma1911

**Comment by saurabh100ni** [comment]
Hey @vaibhavpnimkar ,
Thanks for raising the PR, Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?pli=1#heading=h.69qskjv558bk) to discuss it in the Website Meeting tomorrow at 6:30 PM IST.

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Comment by leecalcote** [comment]
This looks good to me. In addition to the containment of this image, we need for this page to be rewritten / restyled with flex-based, responsive layout of the cards.

**Comment by leecalcote** [comment]
> This looks good to me. In addition to the containment of this image, we need for this page to be rewritten / restyled with flex-based, responsive layout of the cards.

A challenge that you might tackle, @vaibhavpnimkar?

**Comment by Ashparshp** [comment]
> > This looks good to me. In addition to the containment of this image, we need for this page to be rewritten / restyled with flex-based, responsive layout of the cards.
> 
> A challenge that you might tackle, @vaibhavpnimkar?

Great job, @vaibhavpnimkar! The fix for the image looks good. Regarding the additional challenge mentioned by @leecalcote about rewriting/restyling the page with a flex-based, responsive layout of the cards, let us know if you plan to tackle that as well.
If you need any assistance or would like help with the additional challenge mentioned by @leecalcote regarding the page rewrite and styling, feel free to let me know. I'm here to help and collaborate!

**Comment by vaibhavpnimkar** [comment]
> > This looks good to me. In addition to the containment of this image, we need for this page to be rewritten / restyled with flex-based, responsive layout of the cards.
> 
> A challenge that you might tackle, @vaibhavpnimkar?



> > This looks good to me. In addition to the containment of this image, we need for this page to be rewritten / restyled with flex-based, responsive layout of the cards.
> 
> A challenge that you might tackle, @vaibhavpnimkar?

ok i would love take this challenge @leecalcote

**Comment by vaibhavpnimkar** [comment]
> > > This looks good to me. In addition to the containment of this image, we need for this page to be rewritten / restyled with flex-based, responsive layout of the cards.
> > 
> > 
> > A challenge that you might tackle, @vaibhavpnimkar?
> 
> Great job, @vaibhavpnimkar! The fix for the image looks good. Regarding the additional challenge mentioned by @leecalcote about rewriting/restyling the page with a flex-based, responsive layout of the cards, let us know if you plan to tackle that as well. If you need any assistance or would like help with the additional challenge mentioned by @leecalcote regarding the page rewrite and styling, feel free to let me know. I'm here to help and collaborate!

sure will ping you here

**Pull request merged**
