### PR TITLE
Added docs for connections

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Notes for Reviewers**

This PR fixes #

- [x] Connections
- [x] Manage connections
- [ ] Unmanaged connections 
- [x] Lifecycle and state of managed connections
- [ ] Lifecycle and states of unmanaged connections

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
@Yashsharma1911 let's avoid repeating what we have in Meshery Docs.

**Comment by leecalcote** [comment]
> @Yashsharma1911 let's avoid repeating what we have in Meshery Docs.

Links to individual pages where they can read more will work.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
A final pass here would be good, @Yashsharma1911

**Comment by Yashsharma1911** [comment]
> > @Yashsharma1911 let's avoid repeating what we have in Meshery Docs.
> 
> Links to individual pages where they can read more will work.

Ohh okay I'll be adding and giving it final pass

**Pull request closed without merging**
