### PR TITLE
Solved Add alt text to the images in docs #116

### LINKED ISSUE #116: Add alt text to the images in docs
#### Current Behavior
**Currently, we do not have any alt text for 131 images on our site.**
image

#### Expected Behavior
**Please add meaningful alt text to as many images as possible.**

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by surajvast1**
**Notes for Reviewers**

This PR fixes #116 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by iArchitSharma — CHANGES_REQUESTED** [review]
@surajvast1 Can you please keep the original formatting in `hugo.toml` ?

**Comment by surajvast1** [comment]
> @surajvast1 Can you please keep the original formatting in `hugo.toml` ?

As in about the page format or the code please specify your questions if its page format i have already done if its about code then we need to do the changes in toml file by adding alt

**Comment by surajvast1** [comment]
If you think this is complete, could you please merge it? I'm also willing to assist in any way possible."

**Review by iArchitSharma — APPROVED** [review]
LGTM!
Thanks @surajvast1

**Comment by iArchitSharma** [comment]
@surajvast1 make sure to always sign off your commit, otherwise DCO check fails

**Comment by surajvast1** [comment]
Okay I'll make sure that, is it ok for now?

**Comment by leecalcote** [comment]
Excellent!

**Comment by surajvast1** [comment]
Thankyou so much

**Comment by surajvast1** [comment]
Thankyou

**Pull request merged**
