### PR TITLE
Fixed logos when hovered

### LINKED ISSUE #109: The logos when hovered doesn't look good
#### Current Behavior

When we hover on meshmap docs/ night hawk docs under the tutorial section the icons should also get adjusted as dark.

#### Screenshots/Logs

https://github.com/layer5io/docs/assets/85561967/7357d680-4df5-4bbc-b928-c1b30e454594

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Raj100679**
**Notes for Reviewers**

This PR fixes #109 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Raj100679** [comment]
@iArchitSharma @leecalcote Done some small changes, Thanks

**Review by leecalcote — CHANGES_REQUESTED** [review]
My request was that the white versions of each of the logos is used. This proposed change inside of this pull request does not honor that request, but instead manipulates the logos (which is in violation of the brand guidelines) and does not achieve the same results the white versions of the logos. The white versions look different because they have specific opacities configured for different sections of the SVG.

**Comment by iArchitSharma** [comment]
@Raj100679 Please check the brand guidelines - https://layer5.io/company/brand and do the changes and use the white version or the light grey version of logos according to the guidelines.

**Comment by Raj100679** [comment]
Sure thing, will do the necessessary changes, Thanks

**Comment by Raj100679** [comment]
https://github.com/layer5io/docs/assets/85561967/7eafbc87-b7a4-451d-ad98-26f03d26ff4b

@leecalcote @iArchitSharma Is there any logo for meshmap which could be suitable here, I was not able to find it

**Comment by iArchitSharma** [comment]
@Raj100679 By changing `_styles_project.scss`  you are messing all the images in hyperlink changing them to a white color

**Comment by iArchitSharma** [comment]
@Raj100679 if you scroll down you can find download link of meshmap logo assests
But here is the logo anyway:
meshmap-white-icon

**Pull request closed without merging**
