### PR TITLE
Current highlighted nav-links

### LINKED ISSUE #138: Current page nav-link is not highlighted
#### Current Behavior

Currently the nav-links: Cloud and Meshmap are not highlighted when we go `/cloud/` and `/meshmap/`
#### Expected Behavior

The links should be highlighted and disabled. 

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Aniumbott**
**Notes for Reviewers**

This PR fixes #138

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aniumbott** [comment]
> @Aniumbott Products section is still highlighted on home page 

It was there in the figma UI so...

**Comment by iArchitSharma** [comment]
@Aniumbott when it is selected
image

**Comment by Aniumbott** [comment]
> @Aniumbott when it is selected
> image
> 

Oh, I see, Will Update it.

**Comment by iArchitSharma** [comment]
LGTM THANKS!

**Pull request merged**
