### PR TITLE
Fixed highlighting issue of @ keyword

### PR DESCRIPTION
**Pull request by Sathwik-git**
**Notes for Reviewers**
 This PR fixes the #154 highlighted the @ keyword with backticks

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by iArchitSharma** [comment]
@Sathwik-git could you please use `<code style="background-color:#454a51">` instead of `

**Comment by Sathwik-git** [comment]
@iArchitSharma made changes as you mentioned :)

**Comment by leecalcote** [comment]
@Sathwik-git the color of the tagged text isn't the concern of the issue.

**Comment by saurabh100ni** [comment]
Hi @Sathwik-git,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by leecalcote** [comment]
@Sathwik-git there's a lack of understanding of what is needed. Attend tomorrow's meeting and seek clarity. Let's close this out in the meantime.

**Pull request closed without merging**
