### PR TITLE
 [Docs] Includes steps to sign off commits #374 

### LINKED ISSUE #374: [Docs] Include steps to sign off commits
#### Current State
The [CONTRIBUTING-gitflow.md](https://github.com/layer5io/docs/blob/master/CONTRIBUTING-gitflow.md) file currently lacks instructions on how to sign off commits in order to meet the Developer Certificate of Origin (DCO) requirements.

#### Desired State
The guide should include steps for contributors to sign off their commits, following the DCO requirements.
The steps provided in the [Meshery CONTRIBUTING guide](https://docs.meshery.io/project/contributing#general-contribution-flow) can be used as a reference. 

For more details on DCO, see the [DCO](https://developercertificate.org/) file and how it works [here](https://github.com/probot/dco#how-it-works).

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by csengineer1990**
**Notes for Reviewers**
I have added instructions on how to sign off commits to meet the Developer Certificate of Origin (DCO) requirements in the file CONTRIBUTING-gitflow.md. Could you please review it and let me know if there are any issues or if any further adjustments are needed?
This PR fixes  #374

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thanks, @csengineer1990 👍

**Comment by csengineer1990** [comment]
Thank you so much @leecalcote 

I have a small request. Could you kindly label this issue/PR/MR as "Hacktoberfest" or "Hacktoberfest-accepted"?

Thank you for your consideration!

**Comment by leecalcote** [comment]
@csengineer1990 you bet. 👍

**Comment by csengineer1990** [comment]
Thank you so much, @leecalcote! I really appreciate it. Looking forward to contributing further.

**Pull request merged**
