### PR TITLE
Overflow fix

### LINKED ISSUE #25: [Homepage] Background SVGs need clipped
#### Current Behavior
Scroll bars are unnecessarily made visible by background images that extend past the screen.

Screenshot 2023-10-29 at 2 55 53 PM

#### Expected Behavior
Decided homepage needs to avoid overflow and should clip any background images to the current viewport size.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ksauravhash**
**Notes for Reviewers**

This PR fixes #25 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
You made that look easy, @ksauravhash 😄

**Review by leecalcote — CHANGES_REQUESTED** [review]
Uh-oh...
Screenshot 2023-11-01 at 12 54 23 PM

**Comment by ksauravhash** [comment]
> Uh-oh... Screenshot 2023-11-01 at 12 54 23 PM

I thought, it was be design. I will fix that too.

**Comment by ksauravhash** [comment]
image
Is this alright?

**Comment by ksauravhash** [comment]
Check this if this is okay?
image

**Comment by leecalcote** [comment]
@ksauravhash, yes, it seems to be 👍 

The other radial gradient "dash" element needs to have this same thing applied to it. Do you might attending to this in another PR?

**Pull request merged**
