### PR TITLE
broken link updated 

### PR DESCRIPTION
**Pull request by YashrajKupekar17**
**Notes for Reviewers**

This PR fixes #
https://github.com/layer5io/docs/issues/340

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by YashrajKupekar17** [comment]
@hargunkaur286 this is a new pr for my issue. It is according to all the required changes . Please merge it soon

**Comment by YashrajKupekar17** [comment]
Its working .please merge it soon

https://github.com/user-attachments/assets/febb75f9-e004-4e7d-a847-a01cd99adf10

**Comment by Aviral0702** [comment]
@YashrajKupekar17 Please mention the issue you are addressing in the description. It will be easier for the reviewers to refer to the issue you are solving.

**Comment by YashrajKupekar17** [comment]
https://github.com/layer5io/docs/issues/340
this is the link to the issue.
please merge it sooner . Its according to the changes mentioned in the meeting .

**Comment by Ashparshp** [comment]
@YashrajKupekar17, Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
