### PR TITLE
[Docs] New Page for Visualizer Views

### PR DESCRIPTION
**Pull request by nwanduka**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by jameshorton2337** [comment]
Looks good so far. 😉

**Comment by vishalvivekm** [comment]
@nwanduka Let'd discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by iArchitSharma** [comment]
@nwanduka, can you expand the content? It's nice to explain what you can do with Views. Can we also mention how to do it? For example, how you can export views.

**Comment by nwanduka** [comment]
> @nwanduka, can you expand the content? It's nice to explain what you can do with Views. Can we also mention how to do it? For example, how you can export views.

Done @iArchitSharma. How is it now?

**Comment by iArchitSharma** [comment]
Awesome @nwanduka 
can you please do same for other things in managing views

**Comment by nwanduka** [comment]
@iArchitSharma I made a few changes. I'm facing some issues with the screenshots. They load in the markdown preview but not in the netlify preview. I can't figure out why but I think you can. Please review.

**Comment by iArchitSharma** [comment]
@nwanduka 
See the format here : 
image

**Comment by nwanduka** [comment]
Done @iArchitSharma

**Review by iArchitSharma — APPROVED** [review]
Thanks

**Pull request merged**
