### PR TITLE
New Navigation bar is updated

### LINKED ISSUE #127: Update the Navigation bar to new design
#### Current Behavior

This is the issue covering a part of #12 which is the Navigation bar.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

### PR DESCRIPTION
**Pull request by Aniumbott**
**Notes for Reviewers**

This PR fixes #127 

https://github.com/layer5io/docs/assets/76243585/4b4a8a1b-0a93-4a39-b43e-085804c0f650

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by iArchitSharma** [comment]
- Products should be rename to Solutions
- Search bar isn't working

**Comment by saurabh100ni** [comment]
Hi @Aniumbott  ,

Thanks for your PR! 🚀 I encourage you to share this in the Website Meeting today at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the Doc [here](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?pli=1#heading=h.69qskjv558bk) to include this PR.

You're welcome in the meeting today

Cheers, and Happy New Year 🥂,

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Comment by Aniumbott** [comment]
> * Products should be rename to Solutions
> * Search bar isn't working

Ya, I just noticed. It was the problem with the CDN scripts which were required for the dropdown, Anyways I've updated it with a custom script.
Also, I have updated the Products -> Solutions.

**Comment by iArchitSharma** [comment]
@Aniumbott sorry for misunderstanding from my side please change Solutions back to Products

**Comment by iArchitSharma** [comment]
@Aniumbott are you still working on it?

**Comment by Aniumbott** [comment]
yep

**Comment by iArchitSharma** [comment]
@Aniumbott oh great please add Cloud and Meshmap link to the top navbar
image

**Comment by iArchitSharma** [comment]
also when we search the text in search box becomes white, it should remain blackish
image

**Comment by Aniumbott** [comment]
> also when we search the text in search box becomes white, it should remain blackish image

Done 👍

**Comment by Aniumbott** [comment]
> also when we search the text in search box becomes white, it should remain blackish image

Done 👍
Let me know if anything else is required.

**Comment by iArchitSharma** [comment]
on home its working fine but when you go to the Cloud or Meshmap and than click on products, icons aren't showing up
image

**Comment by Aniumbott** [comment]
I thought the static folder is the root for images as per in `_index.md` so I didn't think that the path would be relative, Sorry for this misunderstanding.

**Comment by iArchitSharma** [comment]
@Aniumbott Thank you for this and I would really appreciate if you can fix one last thing i.e. the active nav color which should change based on the page you are in
image

**Comment by iArchitSharma** [comment]
@Aniumbott No update here, lets get this active button issue fixed on next PR

**Review by iArchitSharma — APPROVED** [review]
LGTM!

**Comment by Aniumbott** [comment]
Ok, I will shift to a separate PR. Sorry, I was busy for a few days.

**Comment by iArchitSharma** [comment]
@Aniumbott Please create an issue about it and assign it to yourself

> @Aniumbott No update here, lets get this active button issue fixed on next PR

**Pull request merged**
