### PR TITLE
Bump docsy theme to latest version 0.9.1

### PR DESCRIPTION
**Pull request by deining**
**Notes for Reviewers**

This PR bumps docsy theme to latest released version 0.9.1.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Hi @deining  ,
Thanks for your PR! I encourage you to share this in the Website Meeting today at 7:00 AM CT. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by deining** [comment]
Thanks for your invitation! Due to other commitments, I'm unable to attend. Please use this issue tracker if any further input is needed from my side. Looking forward receiving your review of my PRs!

**Comment by saurabh100ni** [comment]
Thanks for sending the word @deining

**Comment by leecalcote** [comment]
@deining what issues did you see upon upgrade?

**Comment by deining** [comment]
> @deining what issues did you see upon upgrade (if any at all)?

Fortunately, I didn't see any issues when upgrading :smile: .

**Review by nwanduka — COMMENTED** [review]
Thank you for working on this @deining 

I noticed some texts (on the home page) use a font different from the Layer5 brand font. You may want to take a look at that.

image

image

**Comment by leecalcote** [comment]
Good eye, @nwanduka. @deining, I wonder if our current customizations fall outside of the safe zone, so to speak. Are you able to identify where we've gone astray?

**Comment by deining** [comment]
> Thank you for working on this @deining

You are welcome.

> I noticed some texts (on the home page) use a font different from the Layer5 brand font.

With an additional commit, I tried to resolve this. Still not 100% the original layout, though.

**Comment by nwanduka** [comment]
>With an additional commit, I tried to resolve this. Still not 100% the original layout, though.

Looks good now. Thank you @deining

**Comment by leecalcote** [comment]
@iArchitSharma how are we proceeding here?

**Comment by iArchitSharma** [comment]
Fixing this in this PR - https://github.com/layer5io/docs/pull/230

**Pull request closed without merging**
