### PR TITLE
[UI] increase space between two sections of homepage

### LINKED ISSUE #199: [UI] Add spacing between the two sections on homepage
#### Current Behavior
The two sections are very close to each other which makes it look like they are of the same.
image

#### Desired Behavior
Increase the spacing between the two sections shown in the above image

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

### PR DESCRIPTION
**Pull request by ASK-03**
**Notes for Reviewers**

This PR fixes #199 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@iArchitSharma don't forget the headings.

**Comment by iArchitSharma** [comment]
@ASK-03 Heading: Elevate Your Infrastructure with our cloud native services, and join an open-source community for cloud native engineers.
// @ritiksaxena124

**Review by iArchitSharma — CHANGES_REQUESTED** [review]

**Comment by saurabh100ni** [comment]
Hi @ASK-03  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by ASK-03** [comment]
Thanks @iArchitSharma for the PR! Sorry, I was not able to do the changes on time.

**Pull request merged**
