### PR TITLE
[Docs] Add tips and trick: How to animate edges in Meshery Designs

### LINKED ISSUE #327: [Docs] Add tips and trick: How to animate edges in Meshery Designs
#### Current State
Users can animate edges in Meshery Designs by adding an annotation in the relationship definition for edges created in designs.

#### Desired State

Add the following trick to an appropriate page.

Tip:
To enable this animation for an edge, set the animation property of relationship metadata to "marching-ants".

Example filename: edge-firewall.json
Example content:

```json
{                                                                                                                                                                
"schemaVersion": "relationships.meshery.io/v1alpha2",
"version": "v1.0.0",
"kind": "Edge",
"metadata": {
   "description": "A relationship that act as a firewall for ingress and egress traffic from Pods.",
   "animation": "marching-ants",
   "capabilities": {
   "designer": {
      "edit": {
         "style": true,
         "config": false,
         "label": false
         }
      }
   }
},
"model": {
   "name": "kubernetes",
   .....  rest of relationship }
}
```

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by iushdoescode**
**Notes for Reviewers**

This PR fixes #327
Screenshot 2024-07-28 111907

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@iushdoescode Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by jameshorton2337** [comment]
Thank you, @iushdoescode 👏 

@Ashparshp, do you have any feedback for @iushdoescode?

**Review by Ashparshp — COMMENTED** [review]
Please avoid unnecessary tab and space changes, as they make it difficult to review by showing many lines of code changes.

**Comment by Ashparshp** [comment]
@iushdoescode Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by leecalcote — APPROVED** [review]
Thanks, @iushdoescode

**Pull request merged**
