### PR TITLE
[feat] Add option to sort permissions table by roles

### LINKED ISSUE #323: [Docs] Permissions by Role
#### Current State
https://docs.layer5.io/cloud/reference/default-permissions/

#### Desired State
Present the permissions table in Layer5 docs in an alternative format not categorized by Function / Keychain, but by role.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by dragon-slayer875**
**Notes for Reviewers**

This PR fixes #323 

image

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
It'd be helpful if the first column was that of the functionality category; if a new column was added.

**Comment by dragon-slayer875** [comment]
> It'd be helpful if the first column was that of the functionality category; if a new column was added.

Do you mean that the first column should pick from the 'function' column of our permissions sheet?
If yes, then it is infact that very column, I had just renamed the header, but I can name it to functionality/function if that serves our purpose better.

**Comment by leecalcote** [comment]
Checking in...

**Comment by dragon-slayer875** [comment]
Merging the PR to allow contributers working on other related issues to update this table simultaneously.
Will be making a separate PR for the required changes.

**Pull request merged**
