### PR TITLE
Created design-review.md

### LINKED ISSUE #88: [Docs] A seperate page is needed for "Design Reviews"
#### Desired State
A new page is needed for the **Design Reviews** on [Meshmap Documentation](https://docs.layer5.io/meshmap/), [reviewing designs](https://docs.layer5.io/meshmap/designer/comments/) page and the reference of features like [comments](https://docs.layer5.io/meshmap/designer/comments/#:~:text=or%20others%20collaborate.-,Why%20Use%20Comments%3F,-Enhance%20Collaboration) can be taken as a reference to create this page.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by nwanduka**
Page for description of "Design Reviews"

**Notes for Reviewers**

This PR fixes #88 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by iArchitSharma — CHANGES_REQUESTED** [review]
Gif not visible
image

**Comment by nwanduka** [comment]
> Gif not visible image

Check it now.

**Comment by leecalcote** [comment]
What research / tools / methods did you use to put this together, @nwanduka?

**Comment by leecalcote** [comment]
Oh, I see. This is a rewrite of the existing page.

**Comment by leecalcote** [comment]
@nwanduka please only include changes that you've made, otherwise, review is more difficult and take longer to offer feedback.

**Comment by nwanduka** [comment]
Thanks for the feedback @leecalcote. I appreciate your input. Yes, you're correct; the "Design Reviews" page is essentially a rewrite of the existing "Reviewing Designs" page.

When you suggest to only include changes I've made, do you mean to edit the original "Reviewing Designs" page directly so you can see the specific insertions and deletions?

**Comment by leecalcote** [comment]
Victoria Nduka, yes, precisely

**Pull request closed without merging**
