### PR TITLE
Updated _index.md for Reviewing Designs page

### PR DESCRIPTION
**Pull request by nwanduka**
1. Changed subheading to "Three Ways to Add Comments"
2. Reduced display width of screenshots from 1000 to 600
3. Adjusted spacing between screenshots 

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Good work with the structuring and corrections Victoria, can we fix the Display size in screenshots too?

**Comment by nwanduka** [comment]
Thank you. Should I reduce it further? The screenshots width

**Comment by nwanduka** [comment]
I see what you mean now @ saurabh100ni. I'll make some adjustments to the screenshots now.

**Comment by nwanduka** [comment]
@saurabh100ni, how does it look now? Any further adjustments?

**Review by leecalcote — COMMENTED** [review]
@nwanduka please have a look at the changes that I've made. I wasn't able to go through the final section of the doc on best practices, but if you reflect on the changes that I've made, you might consider whether additional changes are needed in the best practices section.

Also, I rephrased one section to be presented as "Tips", which might be duplicative of the purpose of the "best practices" section, so if you need to alter my changes in order to de-duplicate, please do.

**Pull request merged**
