### PR TITLE
[CI] Ignore certain paths in site deployment workflow

### PR DESCRIPTION
**Pull request by leecalcote**
Ignore these paths (no build needed):

paths:
      - '!**'
      - 'docs/**'

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@theBeginner86 look good?

**Comment by leecalcote** [comment]
The site went down yesterday, because an alternative GitHub Pages workflow built and published the site. All that showed up on the public site was the contents of the readme.

**Review by theBeginner86 — APPROVED** [review]
LGTM

**Comment by theBeginner86** [comment]
> The site went down yesterday, because an alternative GitHub Pages workflow built and published the site. All that showed up on the public site was the contents of the readme.

Ohh, I see.
Thanks for fixing.

**Pull request merged**
