### PR TITLE
[Docs Feature] Picture in Modal

### LINKED ISSUE #41: [Docs Feature] Picture in Modal
Also, on the wishlist is to have this or CSS-only capability added to the site - <https://gist.github.com/zjeaton/0cdd7e4bed9d292ab6f3d76b0369f16d> // <@U05T16S16AW>

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1698943090454399?thread_ts=1698940549.402199&cid=C015QJKUMPU)

### PR DESCRIPTION
**Pull request by coder12git**
**Notes for Reviewers**

This PR fixes #41

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by coder12git** [comment]
https://www.loom.com/share/8b0db3ac9b5548a682c46aace2cc4b28?sid=e37bcaaf-9e98-480d-82c9-6cc0a0641cf0

// @leecalcote

**Comment by coder12git** [comment]
https://github.com/layer5io/docs/assets/108334168/2d28aafc-7593-46e0-b4b7-0fbd0139f767

**Comment by leecalcote** [comment]
Thank you for taking this video.

**Comment by coder12git** [comment]
Done the changes

**Review by leecalcote — CHANGES_REQUESTED** [review]
Two issues:

1. Overlapping menu items
2. Dismissal of modal is difficult in that click of the image doesn't seem to dismiss it, nor does there seem to be an "X" to click. 
 
https://github.com/layer5io/docs/assets/7570704/fbde1a4b-c988-49f9-a2c6-237ca6d56cd6

**Comment by coder12git** [comment]
> Two issues:
> 
> 1. Overlapping menu items
> 2. Dismissal of modal is difficult in that click of the image doesn't seem to dismiss it, nor does there seem to be an "X" to click.
> 
>  Screen.Recording.2023-11-10.at.10.18.08.PM.mov

@leecalcote this is an issue with style of the header that's why x-icon is overlapping with header, although that's not an issue with small screen, ok i will fix it

**Comment by abhijeetgauravm** [comment]
Hey @coder12git  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by coder12git** [comment]
@leecalcote done the changes!

**Comment by coder12git** [comment]
@leecalcote done the changes and added a short description in readme about how to display images as a pop up modal.

**Comment by leecalcote** [comment]
Yay!

**Pull request merged**
