### PR TITLE
[Docs] Hyperlink added for each Role name from Permissions Reference page to Roles page

### LINKED ISSUE #321: [Docs] Hyperlink each Role name from Permissions Reference page to Roles page
#### Current State
This page lists permissions for each role, but doesn't offer a link to each role description - https://docs.layer5.io/cloud/reference/default-permissions/

#### Desired State
Hyperlink each Role name from Permissions Reference page to Roles page

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by SAHU-01**
**Notes for Reviewers**

This PR fixes #321

A hyperlink for all available roles in doc has been added and the ones that are not documented in `Roles` for now (_ex: User_) are redirected to the default [roles](https://docs.layer5.io/cloud/security/roles/) page.

Refer to the changes below:

https://github.com/user-attachments/assets/9954fe30-1e72-4e02-a467-f738b69bea50

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@SAHU-01 
Thank you for your contribution.
Let's discuss this on Websites' call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by leecalcote** [comment]
@dragon-slayer875 @Yashsharma1911 your 👀s here, if you would.

**Comment by dragon-slayer875** [comment]
@SAHU-01 Hello! It seems you missed adding support for the other roles based sorted table, so that they can link to the pages.
Would you mind making updates so that is also accounted for?

**Comment by SAHU-01** [comment]
@dragon-slayer875 Could share an example for this?
I'm unable to figure this `other roles based sorted table` out ?

**Comment by dragon-slayer875** [comment]
@SAHU-01 Will you be making a separate PR for this?

**Comment by SAHU-01** [comment]
@dragon-slayer875  yes, I don't have a lot of the recent commit so locally I was unable to check a lot of things, owing to merge conflicts I'll send a fresh PR in a couple of minutes with these changes

**Comment by SAHU-01** [comment]
@dragon-slayer875 you can find the new PR with all the changes here: #338

**Pull request closed without merging**
