### PR TITLE
fix: footer container breaking in some break points

### LINKED ISSUE #286: [Feat]: Improvement in footer when width is smaller
#### Current Behavior
Currently the of the page is looking like this
image
so the problem in this when the width size is smaller some containers like ``resources`` and ``community`` breaking especially in mobile version with the width of below ``400px``

#### Desired Behavior
I think there are 2 solutions:-
1. To make them in same level below 400px 
2. To make all the conta.iner in different level like resources , community , solution and then company. 

For my POV 2 could be better option because in 1st approach there are chances that the same error will show but in different ``breakpoint`` or different width.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

### PR DESCRIPTION
**Pull request by upsaurav12**
**Notes for Reviewers**

This PR fixes #286
In I have fixed some issues like ``company`` container was breaking at some points such as ``850px`` and ``<=400px`` so i have fixed them .
Here are some Results for ``850px``

**Prev**
image
**After**
image

Here are some Results for ``<=400px``

**Before**
image

**After**
image

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by iArchitSharma** [comment]
**Before** looks much better than the **After**

**Comment by iArchitSharma** [comment]
@upsaurav12 please keep the alignment to the left instead of center

**Comment by upsaurav12** [comment]
@iArchitSharma will do it but rest of it any other suggestion on improvement. 
My idea was to utilizr the extra space that was left in right side of the container

**Comment by iArchitSharma** [comment]
> @iArchitSharma will do it but rest of it any other suggestion for improvement? My idea was to utilizr the extra space that was left in right side of the container also image company container should be after Solutions

LGTM now, thanks @upsaurav12

**Comment by upsaurav12** [comment]
Thanks @iArchitSharma First merged PR

**Pull request merged**
