### PR TITLE
fix Text not visible inside Table #279

### PR DESCRIPTION
**Pull request by 2003Aditya**
**Notes for Reviewers**

This PR fixes # 279

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by iArchitSharma** [comment]
@2003Aditya thanks, but adding inline css is not an option

just add this class to table- `td-initial` and it will be fixed

**Comment by 2003Aditya** [comment]
> @2003Aditya thanks, but adding inline css is not an option
> 
> just add this class to table- `td-initial` and it will be fixed

i changed color:white but still it didn't work 
image

**Comment by iArchitSharma** [comment]
@2003Aditya don't change any css, just add the class `td-initial` on the table

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks! Let's use a central class in one of the existing scss files, if we can.

**Comment by iArchitSharma** [comment]
Fixed here - https://github.com/layer5io/docs/pull/303

**Pull request closed without merging**
