### PR TITLE
New feature: A next/previous button for the docs section

### PR DESCRIPTION
**Pull request by iArchitSharma**
image

This feature works well for all md files on same directory, we might have to restructure some of the content in order for this feature to work 
Example: under meshmap designer we have three directories instead of three md files
image

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@iArchitSharma did you open all the issues that we documented?

**Comment by iArchitSharma** [comment]
@leecalcote I am going to now

**Comment by leecalcote** [comment]
@iArchitSharma thanks, but these prev and next buttons are not what I intended to describe.

**Comment by leecalcote** [comment]
example
Screenshot 2024-01-24 at 3 28 52 AM

**Comment by leecalcote** [comment]
@iArchitSharma is this PR still on your todo list?

**Comment by iArchitSharma** [comment]
@leecalcote yes it is and will be done by the end of this week

**Comment by leecalcote** [comment]
Many other Hugo sites have this feature. I’m wondering if this isn’t something intrinsic to the framework that or a readily handy convention that we can use or snippet of code that we can reuse. 

In other words, we don’t need to write this ourselves. This feature should be a quickie.

Please list the existing shortcodes or partials or whatever Hugo capabilities or published packages that you have tried, and that don’t work.

**Comment by iArchitSharma** [comment]
@leecalcote Ready to merge!

**Pull request merged**
