### PR TITLE
bug fixed .Link updated

### PR DESCRIPTION
**Pull request by YashrajKupekar17**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by hargunkaur286** [comment]
@YashrajKupekar17 Thank you for your contribution, let's discuss it in today's website meeting at 5.30 pm IST. Adding this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Comment by YashrajKupekar17** [comment]
@hargunkaur286 Great.
Here's a demo video of the solved issue.

https://github.com/user-attachments/assets/eb73a96a-7af5-4eee-a5b3-d74f949cdf9d

**Comment by hargunkaur286** [comment]
@YashrajKupekar17 Thank you, please make sure to join the call, so that we can discuss and close this issue.

**Comment by YashrajKupekar17** [comment]
I have made the changes in package.json as discussed in the meeting . Please merge the pr

**Comment by hargunkaur286** [comment]
@YashrajKupekar17 Thank you for your contribution. Can you please revert the unnecessary changes in package-lock.json file?

**Comment by YashrajKupekar17** [comment]
@hargunkaur286 I have some issue with the it. I will solve it . I think it will be solved . I need to setup the repo again . it will be done by today

**Pull request closed without merging**
