### PR TITLE
Updated Export Designs page

### PR DESCRIPTION
**Pull request by nwanduka**
Moved the details of Embedding to a separate page

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by iArchitSharma — CHANGES_REQUESTED** [review]
Good as we have new Embedding page in docs we can remove the Embeddng details from export page.
@nwanduka can you please add a link of Embedding Designs page in Embedding section?

**Comment by nwanduka** [comment]
@iArchitSharma, Done.

**Review by iArchitSharma — APPROVED** [review]
LGTM Thanks!

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Did you confirm that the Help button in MeshMap that references this page has been updated, @iArchitSharma?

**Comment by leecalcote** [comment]
Once you have, merge, please.

**Comment by iArchitSharma** [comment]
@leecalcote no, the Help button hasn't been updated till now

**Comment by leecalcote** [comment]
> @leecalcote no, the Help button hasn't been updated till now

Once you have, merge, please.

**Comment by leecalcote** [comment]
> > @leecalcote no, the Help button hasn't been updated till now
> 
> Once you have, merge, please, @iArchitSharma

@iArchitSharma seek @AjaxAueleke's assistance. Let's knock out small items like this quickly.

**Comment by iArchitSharma** [comment]
@AjaxAueleke has started working on the help button

**Comment by leecalcote** [comment]
> @iArchitSharma @nwanduka please confirm that we have kept the reminder to update the corresponding help tooltip in MeshMap. There should be a comment in these docs next to the referenced section that ensures that we avoid broken help links.

This is a 30 second change. @iArchitSharma make sure this happens. Simply update the hyperlink in MeshMap. Let's not drag this out further.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
