### PR TITLE
[Docs] Hyperlink added for each Role name from Permissions Reference page to Roles page

### PR DESCRIPTION
**Pull request by SAHU-01**
**Notes for Reviewers**

This PR fixes https://github.com/layer5io/docs/issues/321

A hyperlink for all available roles in doc has been added and the ones that are not documented in Roles for now (ex: User) are redirected to the default [roles](https://docs.layer5.io/cloud/security/roles/) page.

Refer to the changes below:

https://github.com/user-attachments/assets/4731001d-b838-4aa0-9e87-a18a12c792b5

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by dragon-slayer875** [comment]
@SAHU-01 As stated by Lee in the issue comments, please make it so that the links open in the same tab, rather than a new one.

Moreover, I wonder if you can use string slicing to take the first word from the column header and put in the in the URL, instead of using conditional cases.

Can you try that?

**Comment by SAHU-01** [comment]
@dragon-slayer875 sure let me try this and get back to you real quick!

**Comment by SAHU-01** [comment]
@dragon-slayer875 I'm afraid that wouldn't be possible if you take a closer look at the conditions, you'll see the sections do not follow a generic URL when mapped, so there is a need to map each of them individually, but please correct me if I'm wrong.

**Comment by dragon-slayer875** [comment]
No @SAHU-01 you are right, thanks for trying.
Have you took care to make the links open on the same page instead of a new page?
If yes, we can merge this PR.

**Pull request merged**
